# ================================================================
# UtiliTrack IAM - 5 User Stories Configuration
# ================================================================

# ?? Database ????????????????????????????????????????????????????
spring.datasource.url=jdbc:mysql://localhost:3306/utilitrack_iam?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ?? JPA ?????????????????????????????????????????????????????????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false



# ?? Server ??????????????????????????????????????????????????????
server.port=8081

# ?? JWT ?????????????????????????????????????????????????????????
#uses HMAC (HS256)
jwt.secret=utilitrack-iam-super-secret-key-256bits-long-xxxxxxxxxxxxxxxxxxx 
jwt.expiration=300000000000
#15  mins standard OAuth2 connect


# ?? US002: Login Attempt Lockout ????????????????????????????????
app.login.max-attempts=5
app.login.lockout-minutes=15

# ?? US003: Password Reset ???????????????????????????????????????
app.reset-token.expiry-minutes=30
app.frontend.url=http://localhost:3000

# ?? Mail (US003 - password reset email) ?????????????????????????
# For dev with dev-log-only=true you can comment these out:
# ================= MAIL =================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=heer.enjoy91@gmail.com
spring.mail.password=ajsq nmha jhwn gahr

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



# ?? Logging ?????????????????????????????????????????????????????
logging.level.com.utilitrack=DEBUG
logging.level.org.springframework.security=INFO

# ?? Dev toggles (turn OFF in prod) ??????????????????????????????
app.expose-reset-token-in-response=true
app.mail.dev-log-only=true
server.servlet.context-path=/
spring.web.cors.allowed-origins=http://localhost:3000,http://localhost:4200
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,PATCH,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true
spring.web.cors.max-age=3600

spring.mail.properties.mail.debug=true
logging.level.org.springframework.mail=DEBUG
logging.level.com.sun.mail=DEBUG
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

